name: ZMK Firmware Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build keyboard firmware
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker pull
        run: docker pull ghcr.io/zmkfirmware/zmk-build-arm:latest
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/lib/zmk/
            modules/hal/stm32/
          key: ${{ runner.os }}-west-modules-${{ hashFiles('west.yml') }}
      
      - name: Initialize and update workspace
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace ghcr.io/zmkfirmware/zmk-build-arm:latest /bin/bash -c "west init -l config && west update"

      - name: Build firmware (roba left)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace ghcr.io/zmkfirmware/zmk-build-arm:latest /bin/bash -c "west build -s app -b nice_nano_v2 -- -DSHIELD=roba_left"

      - name: Build firmware (roba right)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace ghcr.io/zmkfirmware/zmk-build-arm:latest /bin/bash -c "west build -s app -b nice_nano_v2 -- -DSHIELD=roba_right"

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/zephyr/zmk.uf2

