name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ZMK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build firmware
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            ghcr.io/zmkfirmware/zmk-build-arm:latest \
            /bin/bash -c "west init -l config && west update && west build -s app -b nice_nano_v2 -- -DSHIELD=roba_left && west build -s app -b nice_nano_v2 -- -DSHIELD=roba_right"
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/zephyr/zmk.uf2

