name: ZMK Firmware Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build keyboard firmware
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zmkfirmware/zmk-build-arm:latest # バージョンをlatestに変更
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/lib/zmk/
            modules/hal/stm32/
          key: ${{ runner.os }}-west-modules-${{ hashFiles('west.yml') }}

      - name: Initialize workspace
        run: west init -l config

      - name: Update modules
        run: west update

      - name: Build firmware
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=roba_left
          west build -s app -b nice_nano_v2 -- -DSHIELD=roba_right

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2

