name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ZMK
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: nice_nano_v2
      shield: roba_left roba_right

