name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ZMK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout ZMK repository
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          ref: main
          path: zmk
      
      - name: Checkout config repository
        uses: actions/checkout@v4
        with:
          path: config

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install west
          
      - name: Build
        run: |
          cd zmk
          west init -l ../config
          west update
          west build -s app -b nice_nano_v2 -- -DSHIELD=roba_left
          west build -s app -b nice_nano_v2 -- -DSHIELD=roba_right
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: zmk/build/zephyr/zmk.uf2

