name: Build ZMK firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build roba firmware
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      boards: nice_nano_v2 nice_nano_v2
      shields: roba_left roba_right

